# Generated by Django 5.2.12 on 2026-04-04 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcs_url', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('nationality', models.CharField(blank=True, max_length=10)),
                ('team', models.CharField(blank=True, max_length=255)),
                ('prev_year_points', models.IntegerField(default=0)),
                ('current_year_points', models.IntegerField(default=0)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-prev_year_points'],
            },
        ),
        migrations.CreateModel(
            name='FantasyTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to=settings.AUTH_USER_MODEL)),
                ('riders', models.ManyToManyField(blank=True, to='api.rider')),
            ],
            options={
                'unique_together': {('user', 'year')},
            },
        ),
    ]
